/**
 * Expo config plugin: permit cleartext HTTP to loopback, and nothing else.
 *
 * Android has blocked cleartext traffic by default since API 28, so a
 * standalone APK cannot reach `http://127.0.0.1:8333` — which is exactly how
 * the app talks to a bot running on the same phone under Termux. Without this
 * the on-device deployment silently fails in a real build while working fine
 * in Expo Go, which permits cleartext.
 *
 * The obvious fix, `android.usesCleartextTraffic: true`, is too broad: it
 * would allow unencrypted traffic to *any* host. This app carries a token that
 * can halt trading, so instead we ship a network security config that
 * whitelists the loopback addresses and leaves the secure-by-default policy in
 * place everywhere else.
 *
 * Note that `android.usesCleartextTraffic` in app.json is silently ignored by
 * current Expo prebuild — setting it there produces no manifest attribute at
 * all. This plugin is the working mechanism.
 */

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const FILE_NAME = 'network_security_config.xml';

const LOOPBACK_HOSTS = ['127.0.0.1', 'localhost', '::1'];

/**
 * Extra hosts that may be reached over plain HTTP.
 *
 * Needed for the VPS deployment: over Tailscale the address is something like
 * 100.101.102.103, which is not loopback, and Android's network security
 * config has no CIDR support — every permitted host must be listed literally.
 * So the host is supplied at build time:
 *
 *   MYP1_CLEARTEXT_HOSTS=100.101.102.103 npx expo prebuild -p android
 *
 * or via `expo.extra.cleartextHosts` in app.json. Anything not listed keeps
 * Android's secure default, so a mistyped address cannot leak the API token
 * over plain HTTP to an arbitrary server.
 */
function extraHosts(config) {
  const fromEnv = (process.env.MYP1_CLEARTEXT_HOSTS || '')
    .split(',')
    .map((h) => h.trim())
    .filter(Boolean);
  const fromConfig = config.extra?.cleartextHosts ?? [];
  return [...new Set([...fromEnv, ...fromConfig])];
}

function buildXml(hosts) {
  const entries = hosts
    .map((host) => `    <domain includeSubdomains="false">${host}</domain>`)
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withLoopbackCleartext.js — do not edit by hand.

  Cleartext is permitted ONLY for the hosts listed here. Everything else keeps
  Android's secure default, so a mistyped server address cannot send the API
  token over plain HTTP to somewhere unintended.

  Add hosts with MYP1_CLEARTEXT_HOSTS=a,b at build time, or
  expo.extra.cleartextHosts in app.json.
-->
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
${entries}
  </domain-config>
  <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;
}

/** Write res/xml/network_security_config.xml into the generated project. */
const withConfigFile = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      const hosts = [...LOOPBACK_HOSTS, ...extraHosts(cfg)];
      fs.writeFileSync(path.join(xmlDir, FILE_NAME), buildXml(hosts), 'utf8');
      // Visible in build logs so a missing host is obvious, not mysterious.
      console.log(`  cleartext HTTP permitted for: ${hosts.join(', ')}`);
      return cfg;
    },
  ]);

/** Point <application> at that config. */
const withManifestAttribute = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:networkSecurityConfig'] = `@xml/${FILE_NAME.replace('.xml', '')}`;
    return cfg;
  });

module.exports = (config) => withManifestAttribute(withConfigFile(config));
